services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: game_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/game_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: change-this-in-production
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_ {}